const foodDatabase = [
    // Ethiopian Cuisine
    { name: "Injera (Teff)", calories: 375, protein: 12, carbs: 73, fats: 2, category: "Ethiopian" },
    { name: "Doro Wat (Chicken Stew)", calories: 280, protein: 25, carbs: 10, fats: 15, category: "Ethiopian" },
    { name: "Misir Wat (Red Lentil Stew)", calories: 220, protein: 14, carbs: 35, fats: 4, category: "Ethiopian" },
    { name: "Shiro Wat (Chickpea Stew)", calories: 250, protein: 15, carbs: 30, fats: 10, category: "Ethiopian" },
    { name: "Tibs (Beef/Lamb Sauté)", calories: 350, protein: 30, carbs: 5, fats: 22, category: "Ethiopian" },
    { name: "Kitfo (Minced Raw Beef)", calories: 400, protein: 28, carbs: 2, fats: 30, category: "Ethiopian" },
    { name: "Gomen (Collard Greens)", calories: 90, protein: 4, carbs: 10, fats: 5, category: "Ethiopian" },
    { name: "Kik Alicha (Split Pea Stew)", calories: 210, protein: 12, carbs: 38, fats: 3, category: "Ethiopian" },
    { name: "Ayib (Ethiopian Cheese)", calories: 150, protein: 14, carbs: 4, fats: 9, category: "Ethiopian" },
    { name: "Firfir (Torn Injera in Sauce)", calories: 320, protein: 10, carbs: 60, fats: 8, category: "Ethiopian" },
    { name: "Chechebsa (Kita Firfir)", calories: 380, protein: 8, carbs: 55, fats: 16, category: "Ethiopian" },
    { name: "Genfo (Porridge)", calories: 450, protein: 12, carbs: 65, fats: 18, category: "Ethiopian" },
    { name: "Timatim Salata (Tomato Salad)", calories: 60, protein: 2, carbs: 8, fats: 3, category: "Ethiopian" },
    { name: "Atakilt Wat (Cabbage, Potato, Carrot)", calories: 120, protein: 3, carbs: 20, fats: 4, category: "Ethiopian" },
    { name: "Fasolia (Green Beans & Carrots)", calories: 110, protein: 3, carbs: 15, fats: 5, category: "Ethiopian" },
    { name: "Bozena Shiro (Shiro with Meat)", calories: 380, protein: 25, carbs: 25, fats: 20, category: "Ethiopian" },
    { name: "Derek Tibs (Crispy Meat)", calories: 420, protein: 35, carbs: 2, fats: 28, category: "Ethiopian" },
    { name: "Minchet Abish (Minced Beef Stew)", calories: 310, protein: 26, carbs: 8, fats: 18, category: "Ethiopian" },
    { name: "Key Wat (Spicy Beef Stew)", calories: 340, protein: 28, carbs: 10, fats: 20, category: "Ethiopian" },
    { name: "Dulet (Tripe and Liver)", calories: 290, protein: 24, carbs: 4, fats: 19, category: "Ethiopian" },
    { name: "Tej (Honey Wine - 1 Glass)", calories: 180, protein: 0, carbs: 25, fats: 0, category: "Ethiopian" },
    { name: "Tella (Traditional Beer - 1 Glass)", calories: 120, protein: 1, carbs: 15, fats: 0, category: "Ethiopian" },

    // International Cuisine & Basics
    { name: "Chicken Breast (Grilled, 100g)", calories: 165, protein: 31, carbs: 0, fats: 3.6, category: "Meat" },
    { name: "Salmon (Grilled, 100g)", calories: 206, protein: 22, carbs: 0, fats: 13, category: "Seafood" },
    { name: "White Rice (Cooked, 1 cup)", calories: 205, protein: 4.3, carbs: 45, fats: 0.4, category: "Grains" },
    { name: "Brown Rice (Cooked, 1 cup)", calories: 216, protein: 5, carbs: 45, fats: 1.8, category: "Grains" },
    { name: "Pasta (Cooked, 1 cup)", calories: 220, protein: 8, carbs: 43, fats: 1.3, category: "Grains" },
    { name: "Pizza (Margherita, 1 slice)", calories: 250, protein: 11, carbs: 30, fats: 10, category: "Italian" },
    { name: "Cheeseburger (Standard)", calories: 300, protein: 15, carbs: 33, fats: 12, category: "Fast Food" },
    { name: "French Fries (Medium)", calories: 365, protein: 4, carbs: 48, fats: 17, category: "Fast Food" },
    { name: "Eggs (Large, Boiled)", calories: 78, protein: 6.3, carbs: 0.6, fats: 5.3, category: "Dairy/Eggs" },
    { name: "Avocado (Half)", calories: 160, protein: 2, carbs: 9, fats: 15, category: "Fruits/Veg" },
    { name: "Banana (Medium)", calories: 105, protein: 1.3, carbs: 27, fats: 0.3, category: "Fruits" },
    { name: "Apple (Medium)", calories: 95, protein: 0.5, carbs: 25, fats: 0.3, category: "Fruits" },
    { name: "Broccoli (Cooked, 1 cup)", calories: 55, protein: 3.7, carbs: 11, fats: 0.6, category: "Vegetables" },
    { name: "Sweet Potato (Baked, 1 medium)", calories: 103, protein: 2, carbs: 24, fats: 0.2, category: "Vegetables" },
    { name: "Oats (Raw, 1/2 cup)", calories: 150, protein: 5, carbs: 27, fats: 3, category: "Grains" },
    { name: "Greek Yogurt (Plain, 150g)", calories: 100, protein: 15, carbs: 6, fats: 0, category: "Dairy" },
    { name: "Almonds (1 oz / 28g)", calories: 164, protein: 6, carbs: 6, fats: 14, category: "Nuts" },
    { name: "Peanut Butter (2 tbsp)", calories: 190, protein: 8, carbs: 6, fats: 16, category: "Nuts/Spreads" },
    { name: "Olive Oil (1 tbsp)", calories: 119, protein: 0, carbs: 0, fats: 13.5, category: "Oils" },
    { name: "Sushi (Salmon Roll, 6 pcs)", calories: 300, protein: 12, carbs: 45, fats: 6, category: "Japanese" },
    { name: "Tacos (Beef, 1 shell)", calories: 210, protein: 12, carbs: 15, fats: 10, category: "Mexican" },
    { name: "Croissant (Butter)", calories: 231, protein: 4, carbs: 26, fats: 12, category: "Bakery" },
    { name: "Steak (Ribeye, 100g)", calories: 291, protein: 24, carbs: 0, fats: 22, category: "Meat" },
    { name: "Pancakes (2 medium)", calories: 170, protein: 4, carbs: 28, fats: 4, category: "Breakfast" },
    { name: "Spaghetti Bolognese (1 serving)", calories: 450, protein: 25, carbs: 55, fats: 15, category: "Italian" },
    { name: "Caesar Salad (with dressing)", calories: 350, protein: 8, carbs: 12, fats: 30, category: "Salads" },
    { name: "Falafel (3 patties)", calories: 170, protein: 6, carbs: 18, fats: 9, category: "Middle Eastern" },
    { name: "Hummus (2 tbsp)", calories: 70, protein: 2, carbs: 4, fats: 5, category: "Middle Eastern" },
    { name: "Pita Bread (1 medium)", calories: 165, protein: 5.5, carbs: 33, fats: 1, category: "Grains" }
];

window.FoodDB = foodDatabase;
